MASON = "application/vnd.mason+json"
LINK_RELATIONS_URL = "/PD/link-relations/"
ERROR_PROFILE = "/profiles/error/"
DIARY_PROFILE = "/profiles/diary/"
PLANT_ITEM_PROFILE = "/profiles/plant_item/"
PLANT_GENERAL_PROFILE = "/profiles/plant_general/"
